banking_and_finance = ["AXISBANK-EQ","HDFCBANK-EQ","ICICIBANK-EQ","IDFCFIRSTB-EQ","INDUSINDBK-EQ","KOTAKBANK-EQ","YESBANK-EQ",
"BANKBARODA-EQ","BANKINDIA-EQ","CANBK-EQ","INDIANB-EQ","PNB-EQ","SBIN-EQ","UNIONBANK-EQ",
"BAJFINANCE-EQ","BAJAJFINSV-EQ","CHOLAFIN-EQ","HDFCAMC-EQ","ICICIGI-EQ","ICICIPRULI-EQ","LTF-EQ",
"LICHSGFIN-EQ","M&MFIN-EQ","MANAPPURAM-EQ","MUTHOOTFIN-EQ","SBICARD-EQ","HDFCLIFE-EQ","SBILIFE-EQ",
"FEDERALBNK-EQ","RBLBANK-EQ"]

automobiles = ["ASHOKLEY-EQ","BAJAJ-AUTO-EQ","BALKRISIND-EQ","BOSCHLTD-EQ","EICHERMOT-EQ","HEROMOTOCO-EQ",
"M&M-EQ","MARUTI-EQ","MOTHERSUMI-EQ","TVSMOTOR-EQ","TIINDIA-EQ"]

oil_and_gas = ["BPCL-EQ","GAIL-EQ","HINDPETRO-EQ","IGL-EQ","IOC-EQ","ONGC-EQ","PETRONET-EQ","RELIANCE-EQ","ATGL-EQ","OIL-EQ"]

it_and_services = ["TCS-EQ","INFY-EQ","WIPRO-EQ","TECHM-EQ","HCLTECH-EQ","LTIM-EQ","LTTS-EQ",
"COFORGE-EQ","MPHASIS-EQ","LTIM-EQ","INTELLECT-EQ","CYIENT-EQ"]

pharmaceuticals = ["CIPLA-EQ","DRREDDY-EQ","SUNPHARMA-EQ","DIVISLAB-EQ","LUPIN-EQ","AUROPHARMA-EQ",
"BIOCON-EQ","GLENMARK-EQ","IPCALAB-EQ","TORNTPHARM-EQ","ZYDUSLIFE-EQ","GRANULES-EQ","SYNGENE-EQ"]

metals_and_mining = ["HINDALCO-EQ","TATASTEEL-EQ","JSWSTEEL-EQ","JINDALSTEL-EQ","SAIL-EQ","NMDC-EQ","NATIONALUM-EQ",
"HINDZINC-EQ","VEDL-EQ","HINDCOPPER-EQ","COALINDIA-EQ"]

chemicals = ["DEEPAKNTR-EQ","PIIND-EQ","NAVINFLUOR-EQ","AARTIIND-EQ","TATACHEM-EQ","COROMANDEL-EQ","UPL-EQ"]

construction_and_cement = ["ULTRACEMCO-EQ","SHREECEM-EQ","GRASIM-EQ","AMBUJACEM-EQ","ACC-EQ",
"DALBHARAT-EQ","RAMCOCEM-EQ"]

consumer_goods = ["ASIANPAINT-EQ","BRITANNIA-EQ","COLPAL-EQ","DABUR-EQ","GODREJCP-EQ","HINDUNILVR-EQ","ITC-EQ",
"MARICO-EQ","NESTLEIND-EQ","PAGEIND-EQ","PIDILITIND-EQ","TATACONSUM-EQ","UBL-EQ"]

utilities = ["TATAPOWER-EQ","ADANIPOWER-EQ","ADANIGREEN-EQ","JSWENERGY-EQ","POWERGRID-EQ","NTPC-EQ",
"SJVN-EQ","NHPC-EQ"]

real_estate = ["DLF-EQ","GODREJPROP-EQ","OBEROIRLTY-EQ","LODHA-EQ","PRESTIGE-EQ"]

telecom = ["BHARTIARTL-EQ","IDEA-EQ","JIOFIN-EQ"]

media = ["ZEEL-EQ","SUNTV-EQ","PVRINOX-EQ"]

retail = ["DMART-EQ","TRENT-EQ","VBL-EQ","NYKAA-EQ"]

capital_goods_and_engineering = ["BHEL-EQ","ABB-EQ","CUMMINSIND-EQ","SIEMENS-EQ","HAL-EQ","CGPOWER-EQ","THERMAX-EQ","LT-EQ"]

transportation_and_logistics = ["CONCOR-EQ","DELHIVERY-EQ","GMRINFRA-EQ","IRCTC-EQ"]

hospital_and_healthcare = ["APOLLOHOSP-EQ","METROPOLIS-EQ","LALPATHLAB-EQ","MAXHEALTH-EQ","FORTIS-EQ"]

miscellaneous = ["RECLTD-EQ","PFC-EQ","CANFINHOME-EQ","MCX-EQ","NAM-INDIA-EQ","CAMS-EQ","CDSL-EQ","POLICYBZR-EQ","PAYTM-EQ",
"SONACOMS-EQ","KEI-EQ","KPITTECH-EQ","POONAWALLA-EQ","BSE-EQ","IRFC-EQ","IRB-EQ","HUDCO-EQ","HFCL-EQ","ALOKINDS-EQ","JUSTDIAL-EQ"]

